// items.js
const ITEM_DB = {
    setup: [
        { id: 'clothes1', name: 'ハートＴ', file: 'clothes_1.png', type: 'setup' },
        { id: 'clothes2', name: 'ビカラ服', file: 'clothes_2.png', type: 'setup' },
        { id: 'clothes3', name: 'キラキラメイド', file: 'clothes_3.png', type: 'setup' },
        { id: 'clothes4', name: 'ぽんちょ', file: 'clothes_4.png', type: 'setup' },
        { id: 'clothes5', name: '全身タイツ（黒）', file: 'clothes_5.png', type: 'setup' },
        { id: 'clothes6', name: '全身タイツ（白）', file: 'clothes_6.png', type: 'setup' },
        { id: 'clothes7', name: 'バニー服（黒）', file: 'clothes_7.png', type: 'setup' },
        { id: 'clothes8', name: 'バニー服（青）', file: 'clothes_8.png', type: 'setup' },
        { id: 'clothes9', name: 'バニー服（白）', file: 'clothes_9.png', type: 'setup' },
        { id: 'clothes10', name: 'バニー服(網タイツ)', file: 'clothes_10.png', type: 'setup' },
        { id: 'clothes11', name: 'バニーボーイ', file: 'clothes_11.png', type: 'setup' },
        { id: 'clothes12', name: '光古戦場ボスの服', file: 'clothes_12.png', type: 'setup' },
        { id: 'clothes13', name: '学生服', file: 'clothes_13.png', type: 'setup' },
        { id: 'clothes14', name: 'ウエディングドレス', file: 'clothes_14.png', type: 'setup' },
        { id: 'clothes15', name: 'タキシード', file: 'clothes_15.png', type: 'setup' },
        { id: 'clothes16', name: 'huku', file: 'clothes_16.png', type: 'setup' },
        { id: 'clothes17', name: 'huku', file: 'clothes_17.png', type: 'setup' },
    ],
    tops: [
        { id: 'tops1', name: '絶対甘党', file: 'tops_1.png', type: 'tops' },
        { id: 'tops2', name: 'ゔぇいんT', file: 'tops_2.png', type: 'tops' },
        { id: 'tops3', name: 'セーラー服', file: 'tops_3.png', type: 'tops' },
        { id: 'tops4', name: '黒猫セット（トップス）', file: 'tops_4.png', type: 'tops' },
        { id: 'tops5', name: 'ナースの服', file: 'tops_5.png', type: 'tops' },
        { id: 'tops6', name: 'トップス6', file: 'tops_6.png', type: 'tops' },
        { id: 'tops7', name: 'トップス7', file: 'tops_7.png', type: 'tops' },
        { id: 'tops8', name: 'トップス8', file: 'tops_8.png', type: 'tops' },
        { id: 'tops9', name: 'トップス9', file: 'tops_9.png', type: 'tops' },
        { id: 'tops10', name: 'トップス10', file: 'tops_10.png', type: 'tops' }
    ],
    bottoms: [
        { id: 'bottoms1', name: 'じーぱん', file: 'bottoms_1.png', type: 'bottoms' },
        { id: 'bottoms2', name: 'るーずそっくす', file: 'bottoms_2.png', type: 'bottoms' },
        { id: 'bottoms3', name: 'みずいろ半ズボン', file: 'bottoms_3.png', type: 'bottoms' },
        { id: 'bottoms4', name: 'ゆあがりタオル', file: 'bottoms_4.png', type: 'bottoms' },
        { id: 'bottoms5', name: '黒猫セット（ボトムス）', file: 'bottoms_5.png', type: 'bottoms' },
        { id: 'bottoms6', name: 'ボトムス6', file: 'bottoms_6.png', type: 'bottoms' },
        { id: 'bottoms7', name: 'ボトムス7', file: 'bottoms_7.png', type: 'bottoms' },
        { id: 'bottoms8', name: 'ボトムス8', file: 'bottoms_8.png', type: 'bottoms' },
        { id: 'bottoms9', name: 'ボトムス9', file: 'bottoms_9.png', type: 'bottoms' },
        { id: 'bottoms10', name: 'ボトムス10', file: 'bottoms_10.png', type: 'bottoms' }
    ],
    acc: [
        { id: 'acc1', name: 'リボン', file: 'acc_1.png', type: 'acc' },
        { id: 'acc2', name: '花飾り', file: 'acc_2.png', type: 'acc' },
        { id: 'acc3', name: 'いぬ', file: 'acc_3.png', type: 'acc' },
        { id: 'acc4', name: '風船', file: 'acc_4.png', type: 'acc' },
        { id: 'acc5', name: 'マフラー', file: 'acc_5.png', type: 'acc' },
        { id: 'acc6', name: 'ねこスリッパ', file: 'acc_6.png', type: 'acc' },
        { id: 'acc7', name: 'オバケ', file: 'acc_7.png', type: 'acc' },
        { id: 'acc8', name: 'ビカラ帽', file: 'acc_8.png', type: 'acc' },
        { id: 'acc9', name: 'ビカラ杖', file: 'acc_9.png', type: 'acc' },
        { id: 'acc10', name: '花火', file: 'acc_10.png', type: 'acc' },
        { id: 'acc11', name: 'チャイナリボン', file: 'acc_11.png', type: 'acc' },
        { id: 'acc12', name: 'うちわぱーしゔぁる', file: 'acc_12.png', type: 'acc' },
        { id: 'acc13', name: 'うちわじーくふりーとさん', file: 'acc_13.png', type: 'acc' },
        { id: 'acc14', name: 'カチューシャわっか', file: 'acc_14.png', type: 'acc' },
        { id: 'acc15', name: 'はね', file: 'acc_15.png', type: 'acc' },
        { id: 'acc16', name: 'ネクタイ', file: 'acc_16.png', type: 'acc' },
        { id: 'acc17', name: 'ヘアピン', file: 'acc_17.png', type: 'acc' },
        { id: 'acc18', name: 'ベレー帽', file: 'acc_18.png', type: 'acc' },
        { id: 'acc19', name: '星バッチ', file: 'acc_19.png', type: 'acc' },
        { id: 'acc20', name: 'リボンブローチ', file: 'acc_20.png', type: 'acc' },
        { id: 'acc21', name: 'スカーフ', file: 'acc_21.png', type: 'acc' },
        { id: 'acc22', name: 'ドラゴンエプロン', file: 'acc_22.png', type: 'acc' },
        { id: 'acc23', name: '両手大根', file: 'acc_23.png', type: 'acc' },
        { id: 'acc24', name: '大根ぼうし', file: 'acc_24.png', type: 'acc' },
        { id: 'acc25', name: '黒バニーカチューシャ', file: 'acc_25.png', type: 'acc' },
        { id: 'acc26', name: '青バニーカチューシャ', file: 'acc_26.png', type: 'acc' },
        { id: 'acc27', name: '白バニーカチューシャ', file: 'acc_27.png', type: 'acc' },
        { id: 'acc28', name: 'ねこみみ（黒）', file: 'acc_28.png', type: 'acc' },
        { id: 'acc29', name: 'ねこみみ（白）', file: 'acc_29.png', type: 'acc' },
        { id: 'acc30', name: 'ねこの鈴（青）', file: 'acc_30.png', type: 'acc' },
        { id: 'acc31', name: 'ねこの鈴（赤）', file: 'acc_31.png', type: 'acc' },
        { id: 'acc32', name: 'ねこの手（黒）', file: 'acc_32.png', type: 'acc' },
        { id: 'acc33', name: 'ねこの手（白）', file: 'acc_33.png', type: 'acc' },
        { id: 'acc34', name: 'ねこの足（黒）', file: 'acc_34.png', type: 'acc' },
        { id: 'acc35', name: 'ねこの足（白）', file: 'acc_35.png', type: 'acc' },
        { id: 'acc36', name: 'しっぽ（黒）', file: 'acc_36.png', type: 'acc' },
        { id: 'acc37', name: 'しっぽ（白）', file: 'acc_37.png', type: 'acc' },
        { id: 'acc38', name: 'むらさきのドリンク', file: 'acc_38.png', type: 'acc' },
        { id: 'acc39', name: 'あかいドリンク', file: 'acc_39.png', type: 'acc' },
        { id: 'acc40', name: 'あおいドリンク', file: 'acc_40.png', type: 'acc' },
        { id: 'acc41', name: 'おれんじのドリンク', file: 'acc_41.png', type: 'acc' },
        { id: 'acc42', name: 'ミルク', file: 'acc_42.png', type: 'acc' },
        { id: 'acc43', name: 'ゆあがりタオル', file: 'acc_43.png', type: 'acc' },
        { id: 'acc44', name: 'ばけつ', file: 'acc_44.png', type: 'acc' },
        { id: 'acc45', name: 'ねこじゃらし', file: 'acc_45.png', type: 'acc' },
        { id: 'acc46', name: '黒猫セット(フェイス)', file: 'acc_46.png', type: 'acc' },
        { id: 'acc47', name: '黒猫セット（手)', file: 'acc_47.png', type: 'acc' },
        { id: 'acc48', name: '黒猫セット（足）', file: 'acc_48.png', type: 'acc' },
        { id: 'acc49', name: 'バニーボーイのカチューシャ', file: 'acc_49.png', type: 'acc' },
        { id: 'acc50', name: '光古戦場ボスカチューシャ', file: 'acc_50.png', type: 'acc' },
        { id: 'acc51', name: 'カクテル', file: 'acc_51.png', type: 'acc' },
        { id: 'acc52', name: '注射器', file: 'acc_52.png', type: 'acc' },
        { id: 'acc53', name: 'エリクシール', file: 'acc_53.png', type: 'acc' },
        { id: 'acc54', name: 'ナース帽', file: 'acc_54.png', type: 'acc' },
        { id: 'acc55', name: 'ナースのくつ', file: 'acc_55.png', type: 'acc' },
        { id: 'acc56', name: 'めがね', file: 'acc_56.png', type: 'acc' },
        { id: 'acc57', name: '学生帽', file: 'acc_57.png', type: 'acc' },
        { id: 'acc58', name: 'ローファー', file: 'acc_58.png', type: 'acc' },
        { id: 'acc59', name: '学生ポシェット', file: 'acc_59.png', type: 'acc' },
        { id: 'acc60', name: 'ウエディングヴェール', file: 'acc_60.png', type: 'acc' },
        { id: 'acc61', name: 'ウエディングブーケ', file: 'acc_61.png', type: 'acc' },
        { id: 'acc62', name: 'aaaa', file: 'acc_62.png', type: 'acc' },
        { id: 'acc63', name: 'aaaa', file: 'acc_63.png', type: 'acc' },
        { id: 'acc64', name: 'aaaa', file: 'acc_64.png', type: 'acc' },
    ],
    bg: [
        { id: 'bg1', name: 'ブルー', file: 'bg_1.png', type: 'bg' },
        { id: 'bg2', name: 'ピンク', file: 'bg_2.png', type: 'bg' },
        { id: 'bg3', name: 'イエロー', file: 'bg_3.png', type: 'bg' },
        { id: 'bg4', name: 'オレンジ', file: 'bg_4.png', type: 'bg' },
        { id: 'bg5', name: 'グリーン', file: 'bg_5.png', type: 'bg' },
        { id: 'bg6', name: 'パープル', file: 'bg_6.png', type: 'bg' },
        { id: 'bg7', name: 'ヴェイン', file: 'bg_7.png', type: 'bg' },
        { id: 'bg8', name: 'ジークフリート', file: 'bg_8.png', type: 'bg' },
        { id: 'bg9', name: 'パーシヴァル', file: 'bg_9.png', type: 'bg' },
        { id: 'bg10', name: '大根（黒）', file: 'bg_10.png', type: 'bg' },
        { id: 'bg11', name: '大根（白）', file: 'bg_11.png', type: 'bg' }
        
        
    ]
};
